on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .vscode/*
      - .github/dependabot.yml
      - .gitattributes
      - .github/delivery.yml
  workflow_despatch:
name: CI
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with:
            # Disabling shallow clone is recommended for improving relevancy of reporting
            fetch-depth: 0

        - uses: actions/setup-node@v2
          with:
            node-version: '12'

        - run: npm install
          name: "Install dependencies"

        - run: npm test
          name: "Run tests"

        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            args: >
                -Dsonar.organization=brunopenso
                -Dsonar.projectKey=69338b20-fd5f-439d-bf2c-2b1473ca5712
                -Dsonar.sources=src
                -Dsonar.coverage.exclusions=**tests**
                -Dsonar.exclusions=**tests**
                -Dsonar.sourceEncoding=UTF-8
                -Dsonar.language=js
                -Dsonar.profile=node
                -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
